/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package java2;

import com.mysql.jdbc.Connection;
import java.awt.HeadlessException;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.ButtonGroup;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
/**
 *
 * @author User
 */
public class Barang extends javax.swing.JFrame {
    
 private Statement stat;
 String objKategori[]={"Pilih kategori dibawah...","Alat Tulis","Kertas","Buku","ATK"};
 private ResultSet rs;
 DefaultTableModel model;
 private String judulKolom[]={"No.","Kode Barang","NamaBarang","Kategori","Satuan","Harga","Jumlah"};
 private String[][] dataBarang;
    /**
     * Creates new form Barang
     */
    public Barang() {
        initComponents();
        setModeltabel();
        view_data();
        
        
        
        for (String object : objKategori){
            cbkategori.addItem(object);
        }
        
        ButtonGroup bG = new ButtonGroup();
         bG.add(rbpbox);
         bG.add(rbpcs);
         bG.add(rbrim);
    
         awal();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtkode = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtnamabarang = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        cbkategori = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();
        rbpcs = new javax.swing.JRadioButton();
        rbpbox = new javax.swing.JRadioButton();
        rbrim = new javax.swing.JRadioButton();
        jLabel6 = new javax.swing.JLabel();
        txtharga = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        txtjumlah = new javax.swing.JTextField();
        btnbatal = new javax.swing.JLabel();
        btnsimpan = new javax.swing.JButton();
        btnhapus = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblBarang = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setText("FORM BARANG");

        jLabel2.setText("Kode Barang");

        jLabel3.setText("Nama Barang");

        jLabel4.setText("Kategori");

        cbkategori.setToolTipText("Pilih kategori");
        cbkategori.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbkategoriActionPerformed(evt);
            }
        });

        jLabel5.setText("Satuan");

        rbpcs.setText("Pcs");

        rbpbox.setText("Box");

        rbrim.setText("Rim");

        jLabel6.setText("Harga");

        txtharga.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txthargaKeyTyped(evt);
            }
        });

        jLabel7.setText("Jumlah");

        txtjumlah.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtjumlahKeyTyped(evt);
            }
        });

        btnbatal.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnbatal.setText("Batal");
        btnbatal.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnbatal.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnbatalMouseClicked(evt);
            }
        });

        btnsimpan.setBackground(new java.awt.Color(0, 104, 245));
        btnsimpan.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        btnsimpan.setForeground(new java.awt.Color(255, 255, 255));
        btnsimpan.setText("Simpan");
        btnsimpan.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnsimpanMouseClicked(evt);
            }
        });

        btnhapus.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        btnhapus.setForeground(new java.awt.Color(255, 0, 0));
        btnhapus.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnhapus.setText("Hapus");
        btnhapus.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnhapus.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnhapus.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnhapusMouseClicked(evt);
            }
        });

        jScrollPane1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jScrollPane1MouseClicked(evt);
            }
        });

        tblBarang.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tblBarang.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblBarangMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblBarang);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(btnsimpan, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(btnbatal, javax.swing.GroupLayout.PREFERRED_SIZE, 259, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnhapus, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(18, 18, 18)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3)
                            .addComponent(txtnamabarang)
                            .addComponent(txtkode, javax.swing.GroupLayout.DEFAULT_SIZE, 363, Short.MAX_VALUE)
                            .addComponent(jLabel4)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel5)
                                .addGap(18, 18, 18)
                                .addComponent(rbpcs)
                                .addGap(31, 31, 31)
                                .addComponent(rbpbox)
                                .addGap(18, 18, 18)
                                .addComponent(rbrim))
                            .addComponent(cbkategori, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                            .addGap(0, 0, Short.MAX_VALUE)
                            .addComponent(jLabel1)
                            .addGap(128, 128, 128))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtharga, javax.swing.GroupLayout.DEFAULT_SIZE, 363, Short.MAX_VALUE)
                            .addComponent(jLabel6)
                            .addComponent(txtjumlah, javax.swing.GroupLayout.DEFAULT_SIZE, 363, Short.MAX_VALUE)
                            .addComponent(jLabel7)))
                    .addGap(19, 19, 19)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(380, Short.MAX_VALUE)
                .addComponent(btnsimpan, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnhapus, javax.swing.GroupLayout.DEFAULT_SIZE, 38, Short.MAX_VALUE)
                    .addComponent(btnbatal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 253, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(19, 19, 19))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jLabel1)
                    .addGap(18, 18, 18)
                    .addComponent(jLabel2)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(txtkode, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(13, 13, 13)
                    .addComponent(jLabel3)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(txtnamabarang, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(13, 13, 13)
                    .addComponent(jLabel4)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(cbkategori, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(18, 18, 18)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel5)
                        .addComponent(rbpcs)
                        .addComponent(rbpbox)
                        .addComponent(rbrim))
                    .addGap(16, 16, 16)
                    .addComponent(jLabel6)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(txtharga, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                    .addComponent(jLabel7)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(txtjumlah, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(389, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cbkategoriActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbkategoriActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbkategoriActionPerformed

    private void txthargaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txthargaKeyTyped
        // TODO add your handling code here:
        char cDigit = evt.getKeyChar();
        if(txtharga.getText().length()<10){
            if(!Character.isDigit(cDigit)){
                evt.consume();
            }
        }else{
            evt.consume();
        }
    }//GEN-LAST:event_txthargaKeyTyped
    private void setModeltabel(){
    // membuat tampilan model tabel
        model = new DefaultTableModel(dataBarang,judulKolom);
        tblBarang.setModel(model);
    }
    
    
    
    private void view_data(){
        model.getDataVector().removeAllElements();
        try {
            int no=1;
            String sql = "select * from barang";
            koneksi objkoneksi=new koneksi();
            Connection con=objkoneksi.bukakoneksi();
            stat = con.createStatement();
            rs = stat.executeQuery(sql);
            while(rs.next()){
            model.addRow(new
            Object[]{no++,rs.getString(1),rs.getString(2),rs.getString(3),rs.getString(4),rs.getString(5),rs.getString(6)});
        }

        } catch (SQLException e) {
        }
    }
    
    
    private void txtjumlahKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtjumlahKeyTyped
        // TODO add your handling code here:
        char cDigit = evt.getKeyChar();
        if(txtjumlah.getText().length()<5){
            if(!Character.isDigit(cDigit)){
                evt.consume();
            }
        }else{
            evt.consume();
        }
    }//GEN-LAST:event_txtjumlahKeyTyped

    private void btnbatalMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnbatalMouseClicked
        // TODO add your handling code here:
        awal();
        
    }//GEN-LAST:event_btnbatalMouseClicked

    private void btnsimpanMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnsimpanMouseClicked
        String KodeValue = txtkode.getText();
        if ( KodeValue == null ){
            simpan();
        }else{
            ubah();
        }
    }//GEN-LAST:event_btnsimpanMouseClicked

    private void jScrollPane1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jScrollPane1MouseClicked
       
        
    }//GEN-LAST:event_jScrollPane1MouseClicked

    private void tblBarangMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblBarangMouseClicked
        DefaultTableModel modelselected = (DefaultTableModel)tblBarang.getModel();
        int row = tblBarang.getSelectedRow();
        
                String tKode =(tblBarang.getModel().getValueAt(row, 1).toString());
                String tNama =(tblBarang.getModel().getValueAt(row, 2).toString());
                String tKategori =(tblBarang.getModel().getValueAt(row, 3).toString());
                String tSatuan =(tblBarang.getModel().getValueAt(row, 4).toString());
                String tHarga =(tblBarang.getModel().getValueAt(row, 5).toString());
                String tJumlah =(tblBarang.getModel().getValueAt(row, 6).toString());
                
                txtkode.setText(tKode);
                txtkode.setEnabled(false);
                txtnamabarang.setText(tNama);
                txtharga.setText(tHarga);
                txtjumlah.setText(tJumlah);
                btnhapus.setEnabled(true);
                btnsimpan.setEnabled(true);
                btnsimpan.setText("Ubah");
                
                cbkategori.setSelectedItem(tKategori);
            switch (tSatuan) {
                case "pcs":
                    rbpcs.setSelected(true);
                    break;
                case "box":
                    rbpbox.setSelected(true);
                    break;
                default:
                    rbrim.setSelected(true);
                    break;
            }
    }//GEN-LAST:event_tblBarangMouseClicked

    private void btnhapusMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnhapusMouseClicked
        int dialogResult;
        dialogResult = JOptionPane.showConfirmDialog(null, "Yakin mau menghapus?");
        if ( dialogResult == JOptionPane.YES_OPTION) {
            try{
                koneksi objkoneksi=new koneksi();
                Connection con=objkoneksi.bukakoneksi();
                String sql="DELETE from barang where kodebarang='"+txtkode.getText()+"' ";
                stat = con.createStatement();
                stat.executeUpdate(sql);

                JOptionPane.showMessageDialog(null, "Data Berhasil dihapus");
                awal();
                view_data();
            } catch (Exception e) {
                System.out.println("gagal="+e.getMessage());
            }
        }else{
            awal();
        }
    }//GEN-LAST:event_btnhapusMouseClicked

    private void ubah(){
        if(cbkategori.getSelectedIndex()!=0){
            String satuan;
            if(rbpcs.isSelected()){
                satuan = "pcs";
            }else if(rbpbox.isSelected()){
                satuan = "box";
                }else if(rbrim.isSelected()){
                    satuan = "rim";
                    }else{
                        satuan = null;
                    }
            try{
                koneksi objkoneksi=new koneksi();
                Connection con=objkoneksi.bukakoneksi();
                String sql="UPDATE barang SET namabarang='"+txtnamabarang.getText()+"',kategori='"+cbkategori.getSelectedItem()+"',"+ " satuan='"+satuan+"', harga='"+txtharga.getText()+"',jumlah='"+txtjumlah.getText()+"' where kodebarang='"+txtkode.getText()+"' ";
                stat = con.createStatement();
                stat.executeUpdate(sql);
                javax.swing.JOptionPane.showMessageDialog(null, "Data Berhasil diubah");
                awal();


                DefaultTableModel modeltable;
                modeltable = (DefaultTableModel)tblBarang.getModel();
                modeltable.setRowCount(0);

                view_data();
            } catch (HeadlessException | SQLException e) {
                System.out.println("gagal="+e.getMessage());
            }
        
        }else{
            JOptionPane.showMessageDialog(null, "Pilih kategori barang","notifikasi",2);
        }
    }
    
    private void simpan(){
        String satuan;
        if(cbkategori.getSelectedIndex()!=0){
                if(rbpcs.isSelected()){
                    satuan = "pcs";
                }else if(rbpbox.isSelected()){
                    satuan = "box";
                }else{
                    satuan = "rim";
                }
            try{
                koneksi objkoneksi=new koneksi();
                Connection con =objkoneksi.bukakoneksi();
                String sql="INSERT INTO barang VALUES('"+txtkode.getText()+"','"+txtnamabarang.getText()+"','"+cbkategori.getSelectedItem()+"','"+satuan+"','"+txtharga.getText()+"','"+txtjumlah.getText()+"')";
                stat = con.createStatement();
                stat.execute(sql);

                JOptionPane.showMessageDialog(null, "Data Berhasil di Input");

                awal();

                DefaultTableModel modeltable;
                modeltable = (DefaultTableModel)tblBarang.getModel();
                modeltable.setRowCount(0);
                view_data();

            } catch (HeadlessException | SQLException e){
                System.out.println("gagal="+e.getMessage());
            }
        }else{
            JOptionPane.showMessageDialog(null, "Pilih kategori barang","notifikasi",2);
        }
    }
    
    private void awal(){
        txtkode.setText("");
        txtkode.setEnabled(true);
        txtnamabarang.setText("");
        txtharga.setText("");
        txtjumlah.setText("");
        cbkategori.setSelectedIndex(0);
        rbpcs.setSelected(false);
        rbpbox.setSelected(false);
        rbrim.setSelected(false);
        txtkode.requestFocus();
        
        btnhapus.setEnabled(false);
        btnsimpan.setEnabled(true);
        btnsimpan.setText("Simpan");
        btnbatal.setEnabled(true);
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Barang.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Barang.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Barang.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Barang.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Barang().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel btnbatal;
    private javax.swing.JLabel btnhapus;
    private javax.swing.JButton btnsimpan;
    private javax.swing.JComboBox<String> cbkategori;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JRadioButton rbpbox;
    private javax.swing.JRadioButton rbpcs;
    private javax.swing.JRadioButton rbrim;
    private javax.swing.JTable tblBarang;
    private javax.swing.JTextField txtharga;
    private javax.swing.JTextField txtjumlah;
    private javax.swing.JTextField txtkode;
    private javax.swing.JTextField txtnamabarang;
    // End of variables declaration//GEN-END:variables
}
